# Generated by Django 4.0.6 on 2022-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedimage_height_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='available_heights',
            field=models.ManyToManyField(blank=True, to='api.availableheight'),
        ),
    ]
